services:
  api_gateway_staging:
    container_name: Mini_Tweeter_api_gateway_staging
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    environment:
      - ENVIRONMENT=staging
      - LOG_LEVEL=debug
      - HTTP_PORT=8000
      - USER_SERVICE_HOST=localhost
      - USER_SERVICE_PORT=8082
      - TWEET_SERVICE_HOST=localhost
      - TWEET_SERVICE_PORT=8083
      - LIKE_SERVICE_HOST=localhost
      - LIKE_SERVICE_PORT=8084
      - FANOUT_SERVICE_HOST=localhost
      - FANOUT_SERVICE_PORT=8085
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - RABBITMQ_HOST=localhost
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - ACCESS_TOKEN_SECRET=secret
      - REFRESH_TOKEN_SECRET=secret
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 10s
    restart: on-failure
    networks:
      - Mini-Tweeter-network

networks:
  Mini-Tweeter-network:
    external: true