services:
  backend:
    container_name: Mini_Tweeter_api_gateway_production
    # image: ghcr.io/saidakbarpardaboyev/mini-tweeter-api-gateway/app:production  # 🔹 Always use latest pulled image
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HTTP_PORT=8000
      - USER_SERVICE_HOST=user_service
      - USER_SERVICE_PORT=8082
      - TWEET_SERVICE_HOST=tweet_service
      - TWEET_SERVICE_PORT=8083
      - LIKE_SERVICE_HOST=like_service
      - LIKE_SERVICE_PORT=8083
      - FANOUT_SERVICE_HOST=fanout_service
      - FANOUT_SERVICE_PORT=8083
      - ACCESS_TOKEN_SECRET=secret
      - REFRESH_TOKEN_SECRET=secret
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 10s
    restart: on-failure
    networks:
      - Mini-Tweeter-network

networks:
  Mini-Tweeter-network:
    external: true